"""Validation data constants for tv-scraper."""

from typing import Literal

EXCHANGE_LITERAL = Literal[
    "ADX",
    "ALOR",
    "AMEX",
    "ASX",
    "ATHEX",
    "BAHRAIN",
    "BASESWAP",
    "BCBA",
    "BCS",
    "BELEX",
    "BER",
    "BET",
    "BINANCE",
    "BINANCEUS",
    "BINGX",
    "BIST",
    "BISWAP",
    "BITAZZA",
    "BITBNS",
    "BITCOKE",
    "BITFINEX",
    "BITFLYER",
    "BITGET",
    "BITHUMB",
    "BITKUB",
    "BITMART",
    "BITMEX",
    "BITPANDAPRO",
    "BITRUE",
    "BITSTAMP",
    "BITTREX",
    "BITVAVO",
    "BIVA",
    "BLACKBULL",
    "BLOFIN",
    "BME",
    "BMFBOVESPA",
    "BMV",
    "BSE",
    "BSSE",
    "BTSE",
    "BVB",
    "BVC",
    "BVCV",
    "BVL",
    "BVMT",
    "BX",
    "BYBIT",
    "CAMELOT",
    "CAMELOT3ARBITRUM",
    "CAPITALCOM",
    "CBOE",
    "CBOT",
    "CBOT_MINI",
    "CEXIO",
    "CFFEX",
    "CITYINDEX",
    "CME",
    "CME_MINI",
    "COINBASE",
    "COINEX",
    "COMEX",
    "COMEX_MINI",
    "CRYPTO",
    "CRYPTOCAP",
    "CRYPTOCOM",
    "CRYPTO_SCAN",
    "CSE",
    "CSECY",
    "CSELK",
    "CSEMA",
    "CURRENCYCOM",
    "CURVE",
    "DELTA",
    "DERIBIT",
    "DFM",
    "DJ",
    "DSEBD",
    "DUS",
    "DYDX",
    "EASYMARKETS",
    "ECONOMICS",
    "EGX",
    "EIGHTCAP",
    "EUREX",
    "EURONEXT",
    "EUROTLX",
    "EXMO",
    "FINRA",
    "FOREXCOM",
    "FSE",
    "FTSEMYX",
    "FTX",
    "FWB",
    "FX",
    "FXCM",
    "FXOPEN",
    "FX_IDC",
    "GATEIO",
    "GEMINI",
    "GETTEX",
    "GLOBALPRIME",
    "GPW",
    "HAM",
    "HAN",
    "HITBTC",
    "HKEX",
    "HNX",
    "HONEYSWAP",
    "HONEYSWAPPOLYGON",
    "HOSE",
    "HSI",
    "HTX",
    "HUOBI",
    "ICEAD",
    "ICEEUR",
    "ICESG",
    "ICEUS",
    "IDX",
    "INDEX",
    "JSE",
    "KATANA",
    "KRAKEN",
    "KRX",
    "KSE",
    "KUCOIN",
    "LS",
    "LSE",
    "LSIN",
    "LSX",
    "LUXSE",
    "MATBAROFEX",
    "MCX",
    "MERCADO",
    "MEXC",
    "MGEX",
    "MIL",
    "MMFINANCE",
    "MOEX",
    "MUN",
    "MYX",
    "NAG",
    "NASDAQ",
    "NASDAQDUBAI",
    "NCDEX",
    "NEO",
    "NEWCONNECT",
    "NGM",
    "NSE",
    "NSEKE",
    "NSENG",
    "NYMEX",
    "NYMEX_MINI",
    "NYSE",
    "NZX",
    "OANDA",
    "OKCOIN",
    "OKX",
    "OMXCOP",
    "OMXHEX",
    "OMXICE",
    "OMXRSE",
    "OMXSTO",
    "OMXTSE",
    "OMXVSE",
    "ORCA",
    "OSE",
    "OSL",
    "OTC",
    "PANCAKESWAP",
    "PANCAKESWAP3BSC",
    "PANCAKESWAP3ETH",
    "PANGOLIN",
    "PEPPERSTONE",
    "PHEMEX",
    "PHILLIPNOVA",
    "PIONEX",
    "POLONIEX",
    "PSE",
    "PSECZ",
    "PSX",
    "PULSEX",
    "QSE",
    "QUICKSWAP",
    "QUICKSWAP3POLYGON",
    "QUICKSWAP3POLYGONZKEVM",
    "RAYDIUM",
    "RUS",
    "SAPSE",
    "SAXO",
    "SET",
    "SGX",
    "SHFE",
    "SIX",
    "SKILLING",
    "SP",
    "SPARKS",
    "SPOOKYSWAP",
    "SSE",
    "SUSHISWAP",
    "SUSHISWAPPOLYGON",
    "SWB",
    "SZSE",
    "TADAWUL",
    "TAIFEX",
    "TASE",
    "TFEX",
    "TFX",
    "THRUSTER3",
    "TIMEX",
    "TOCOM",
    "TOKENIZE",
    "TPEX",
    "TRADEGATE",
    "TRADERJOE",
    "TRADESTATION",
    "TSE",
    "TSX",
    "TSXV",
    "TVC",
    "TWSE",
    "UNISWAP",
    "UNISWAP3ARBITRUM",
    "UNISWAP3AVALANCHE",
    "UNISWAP3BASE",
    "UNISWAP3BSC",
    "UNISWAP3ETH",
    "UNISWAP3OPTIMISM",
    "UNISWAP3POLYGON",
    "UPBIT",
    "UPCOM",
    "VANTAGE",
    "VELODROME",
    "VERSEETH",
    "VIE",
    "VVSFINANCE",
    "WAGYUSWAP",
    "WHITEBIT",
    "WOONETWORK",
    "XETR",
    "XEXCHANGE",
    "ZOOMEX",
]

TIMEFRAME_LITERAL = Literal[
    "1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1w", "1M"
]

AREA_LITERAL = Literal["world", "americas", "europe", "asia", "oceania", "africa"]

LANGUAGE_LITERAL = Literal[
    "English",
    "German",
    "French",
    "Spanish",
    "Italian",
    "Portuguese",
    "Russian",
    "Japanese",
    "Korean",
    "Arabic",
    "Hindi",
    "Swedish",
    "Turkish",
    "Thai",
    "Vietnamese",
    "Indonesian",
    "Persian",
    "Chinese",
    "Malay",
    "Greek",
    "Hebrew",
]

NEWS_COUNTRY_LITERAL = Literal[
    "AE",
    "AO",
    "AR",
    "AT",
    "AU",
    "BD",
    "BE",
    "BG",
    "BH",
    "BR",
    "BW",
    "CA",
    "CH",
    "CL",
    "CN",
    "CO",
    "CY",
    "CZ",
    "DE",
    "DK",
    "EE",
    "EG",
    "ES",
    "ET",
    "EU",
    "FI",
    "FR",
    "GB",
    "GH",
    "GR",
    "HK",
    "HR",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JP",
    "KE",
    "KR",
    "KW",
    "LK",
    "LT",
    "LU",
    "LV",
    "MA",
    "MU",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NG",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PE",
    "PH",
    "PK",
    "PL",
    "PT",
    "QA",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "TH",
    "TN",
    "TR",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "VE",
    "VN",
    "ZA",
    "ZM",
    "ZW",
]

NEWS_CORP_ACTIVITY_LITERAL = Literal[
    "credit_ratings",
    "dividends",
    "earnings",
    "earnings_calls",
    "esg",
    "insider_trading",
    "ipo",
    "management",
    "mergers_and_acquisitions",
    "ownership_changes",
    "recommendation",
    "share_buybacks",
    "strategy_business_products",
]

NEWS_ECONOMIC_CATEGORY_LITERAL = Literal[
    "business",
    "consumer",
    "gdp",
    "government",
    "health",
    "housing",
    "labor",
    "money",
    "prices",
    "taxes",
    "trade",
]

NEWS_MARKET_LITERAL = Literal[
    "bond",
    "corp_bond",
    "crypto",
    "economic",
    "etf",
    "forex",
    "futures",
    "index",
    "stock",
]

NEWS_PROVIDER_LITERAL = Literal[
    "99Bitcoins",
    "acceswire",
    "acn",
    "barchart",
    "beincrypto",
    "bravenewcoin",
    "chainwire",
    "cme_group",
    "coindar",
    "coinmarketcal",
    "coinpedia",
    "cointelegraph",
    "cryptobriefing",
    "cryptonews",
    "dow-jones",
    "dpa_afx",
    "eqs",
    "etfcom",
    "financemagnates",
    "financewire",
    "forexlive",
    "globenewswire",
    "gurufocus",
    "investorplace",
    "invezz",
    "jcn",
    "leverage_shares",
    "macenews",
    "market-watch",
    "marketbeat",
    "marketindex",
    "miranda_partners",
    "modular_finance",
    "moneycontrol",
    "nbd",
    "newsbtc",
    "pressetext",
    "quartr",
    "reuters",
    "sharecast",
    "smallcaps",
    "stockstory",
    "stocktwits",
    "the_block",
    "thenewswire",
    "tmx_newsfile",
    "trading-economics",
    "tradingview",
    "u_today",
    "zacks",
    "zawya",
]

NEWS_SECTOR_LITERAL = Literal[
    "Commercial Services",
    "Communications",
    "Consumer Durables",
    "Consumer Non-Durables",
    "Consumer Services",
    "Distribution Services",
    "Electronic Technology",
    "Energy Minerals",
    "Finance",
    "Government",
    "Health Services",
    "Health Technology",
    "Industrial Services",
    "Miscellaneous",
    "Non-Energy Minerals",
    "Process Industries",
    "Producer Manufacturing",
    "Retail Trade",
    "Technology Services",
    "Transportation",
    "Utilities",
]


EXCHANGES: list[str] = [
    "ADX",
    "ALOR",
    "AMEX",
    "ASX",
    "ATHEX",
    "BAHRAIN",
    "BASESWAP",
    "BCBA",
    "BCS",
    "BELEX",
    "BER",
    "BET",
    "BINANCE",
    "BINANCEUS",
    "BINGX",
    "BIST",
    "BISWAP",
    "BITAZZA",
    "BITBNS",
    "BITCOKE",
    "BITFINEX",
    "BITFLYER",
    "BITGET",
    "BITHUMB",
    "BITKUB",
    "BITMART",
    "BITMEX",
    "BITPANDAPRO",
    "BITRUE",
    "BITSTAMP",
    "BITTREX",
    "BITVAVO",
    "BIVA",
    "BLACKBULL",
    "BLOFIN",
    "BME",
    "BMFBOVESPA",
    "BMV",
    "BSE",
    "BSSE",
    "BTSE",
    "BVB",
    "BVC",
    "BVCV",
    "BVL",
    "BVMT",
    "BX",
    "BYBIT",
    "CAMELOT",
    "CAMELOT3ARBITRUM",
    "CAPITALCOM",
    "CBOE",
    "CBOT",
    "CBOT_MINI",
    "CEXIO",
    "CFFEX",
    "CITYINDEX",
    "CME",
    "CME_MINI",
    "COINBASE",
    "COINEX",
    "COMEX",
    "COMEX_MINI",
    "CRYPTO",
    "CRYPTOCAP",
    "CRYPTOCOM",
    "CRYPTO_SCAN",
    "CSE",
    "CSECY",
    "CSELK",
    "CSEMA",
    "CURRENCYCOM",
    "CURVE",
    "DELTA",
    "DERIBIT",
    "DFM",
    "DJ",
    "DSEBD",
    "DUS",
    "DYDX",
    "EASYMARKETS",
    "ECONOMICS",
    "EGX",
    "EIGHTCAP",
    "EUREX",
    "EURONEXT",
    "EUROTLX",
    "EXMO",
    "FINRA",
    "FOREXCOM",
    "FSE",
    "FTSEMYX",
    "FTX",
    "FWB",
    "FX",
    "FXCM",
    "FXOPEN",
    "FX_IDC",
    "GATEIO",
    "GEMINI",
    "GETTEX",
    "GLOBALPRIME",
    "GPW",
    "HAM",
    "HAN",
    "HITBTC",
    "HKEX",
    "HNX",
    "HONEYSWAP",
    "HONEYSWAPPOLYGON",
    "HOSE",
    "HSI",
    "HTX",
    "HUOBI",
    "ICEAD",
    "ICEEUR",
    "ICESG",
    "ICEUS",
    "IDX",
    "INDEX",
    "JSE",
    "KATANA",
    "KRAKEN",
    "KRX",
    "KSE",
    "KUCOIN",
    "LS",
    "LSE",
    "LSIN",
    "LSX",
    "LUXSE",
    "MATBAROFEX",
    "MCX",
    "MERCADO",
    "MEXC",
    "MGEX",
    "MIL",
    "MMFINANCE",
    "MOEX",
    "MUN",
    "MYX",
    "NAG",
    "NASDAQ",
    "NASDAQDUBAI",
    "NCDEX",
    "NEO",
    "NEWCONNECT",
    "NGM",
    "NSE",
    "NSEKE",
    "NSENG",
    "NYMEX",
    "NYMEX_MINI",
    "NYSE",
    "NZX",
    "OANDA",
    "OKCOIN",
    "OKX",
    "OMXCOP",
    "OMXHEX",
    "OMXICE",
    "OMXRSE",
    "OMXSTO",
    "OMXTSE",
    "OMXVSE",
    "ORCA",
    "OSE",
    "OSL",
    "OTC",
    "PANCAKESWAP",
    "PANCAKESWAP3BSC",
    "PANCAKESWAP3ETH",
    "PANGOLIN",
    "PEPPERSTONE",
    "PHEMEX",
    "PHILLIPNOVA",
    "PIONEX",
    "POLONIEX",
    "PSE",
    "PSECZ",
    "PSX",
    "PULSEX",
    "QSE",
    "QUICKSWAP",
    "QUICKSWAP3POLYGON",
    "QUICKSWAP3POLYGONZKEVM",
    "RAYDIUM",
    "RUS",
    "SAPSE",
    "SAXO",
    "SET",
    "SGX",
    "SHFE",
    "SIX",
    "SKILLING",
    "SP",
    "SPARKS",
    "SPOOKYSWAP",
    "SSE",
    "SUSHISWAP",
    "SUSHISWAPPOLYGON",
    "SWB",
    "SZSE",
    "TADAWUL",
    "TAIFEX",
    "TASE",
    "TFEX",
    "TFX",
    "THRUSTER3",
    "TIMEX",
    "TOCOM",
    "TOKENIZE",
    "TPEX",
    "TRADEGATE",
    "TRADERJOE",
    "TRADESTATION",
    "TSE",
    "TSX",
    "TSXV",
    "TVC",
    "TWSE",
    "UNISWAP",
    "UNISWAP3ARBITRUM",
    "UNISWAP3AVALANCHE",
    "UNISWAP3BASE",
    "UNISWAP3BSC",
    "UNISWAP3ETH",
    "UNISWAP3OPTIMISM",
    "UNISWAP3POLYGON",
    "UPBIT",
    "UPCOM",
    "VANTAGE",
    "VELODROME",
    "VERSEETH",
    "VIE",
    "VVSFINANCE",
    "WAGYUSWAP",
    "WHITEBIT",
    "WOONETWORK",
    "XETR",
    "XEXCHANGE",
    "ZOOMEX",
]

INDICATORS: list[str] = [
    "Recommend.Other",
    "Recommend.All",
    "Recommend.MA",
    "RSI",
    "RSI[1]",
    "Stoch.K",
    "Stoch.D",
    "Stoch.K[1]",
    "Stoch.D[1]",
    "CCI20",
    "CCI20[1]",
    "ADX",
    "ADX+DI",
    "ADX-DI",
    "ADX+DI[1]",
    "ADX-DI[1]",
    "AO",
    "AO[1]",
    "AO[2]",
    "Mom",
    "Mom[1]",
    "MACD.macd",
    "MACD.signal",
    "Rec.Stoch.RSI",
    "Stoch.RSI.K",
    "Rec.WR",
    "W.R",
    "Rec.BBPower",
    "BBPower",
    "Rec.UO",
    "UO",
    "EMA10",
    "close",
    "SMA10",
    "EMA20",
    "SMA20",
    "EMA30",
    "SMA30",
    "EMA50",
    "SMA50",
    "EMA100",
    "SMA100",
    "EMA200",
    "SMA200",
    "Rec.Ichimoku",
    "Ichimoku.BLine",
    "Rec.VWMA",
    "VWMA",
    "Rec.HullMA9",
    "HullMA9",
    "Pivot.M.Classic.S3",
    "Pivot.M.Classic.S2",
    "Pivot.M.Classic.S1",
    "Pivot.M.Classic.Middle",
    "Pivot.M.Classic.R1",
    "Pivot.M.Classic.R2",
    "Pivot.M.Classic.R3",
    "Pivot.M.Fibonacci.S3",
    "Pivot.M.Fibonacci.S2",
    "Pivot.M.Fibonacci.S1",
    "Pivot.M.Fibonacci.Middle",
    "Pivot.M.Fibonacci.R1",
    "Pivot.M.Fibonacci.R2",
    "Pivot.M.Fibonacci.R3",
    "Pivot.M.Camarilla.S3",
    "Pivot.M.Camarilla.S2",
    "Pivot.M.Camarilla.S1",
    "Pivot.M.Camarilla.Middle",
    "Pivot.M.Camarilla.R1",
    "Pivot.M.Camarilla.R2",
    "Pivot.M.Camarilla.R3",
    "Pivot.M.Woodie.S3",
    "Pivot.M.Woodie.S2",
    "Pivot.M.Woodie.S1",
    "Pivot.M.Woodie.Middle",
    "Pivot.M.Woodie.R1",
    "Pivot.M.Woodie.R2",
    "Pivot.M.Woodie.R3",
    "Pivot.M.Demark.S1",
    "Pivot.M.Demark.Middle",
    "Pivot.M.Demark.R1",
]

AREAS: dict[str, str] = {
    "world": "WLD",
    "americas": "AME",
    "europe": "EUR",
    "asia": "ASI",
    "oceania": "OCN",
    "africa": "AFR",
}

LANGUAGES: dict[str, str] = {
    "English": "en",
    "German": "de",
    "French": "fr",
    "Spanish": "es",
    "Italian": "it",
    "Portuguese": "pt",
    "Russian": "ru",
    "Japanese": "ja",
    "Korean": "ko",
    "Arabic": "ar",
    "Hindi": "hi",
    "Swedish": "sv",
    "Turkish": "tr",
    "Thai": "th",
    "Vietnamese": "vi",
    "Indonesian": "id",
    "Persian": "fa",
    "Chinese": "ch",
    "Malay": "ms",
    "Greek": "el",
    "Hebrew": "he",
}

NEWS_PROVIDERS: list[str] = [
    "99Bitcoins",
    "acceswire",
    "acn",
    "barchart",
    "beincrypto",
    "bravenewcoin",
    "chainwire",
    "cme_group",
    "coindar",
    "coinmarketcal",
    "coinpedia",
    "cointelegraph",
    "cryptobriefing",
    "cryptonews",
    "dow-jones",
    "dpa_afx",
    "eqs",
    "etfcom",
    "financemagnates",
    "financewire",
    "forexlive",
    "globenewswire",
    "gurufocus",
    "investorplace",
    "invezz",
    "jcn",
    "leverage_shares",
    "macenews",
    "market-watch",
    "marketbeat",
    "marketindex",
    "miranda_partners",
    "modular_finance",
    "moneycontrol",
    "nbd",
    "newsbtc",
    "pressetext",
    "quartr",
    "reuters",
    "sharecast",
    "smallcaps",
    "stockstory",
    "stocktwits",
    "the_block",
    "thenewswire",
    "tmx_newsfile",
    "trading-economics",
    "tradingview",
    "u_today",
    "zacks",
    "zawya",
]

NEWS_COUNTRIES: list[str] = [
    "AE",
    "AO",
    "AR",
    "AT",
    "AU",
    "BD",
    "BE",
    "BG",
    "BH",
    "BR",
    "BW",
    "CA",
    "CH",
    "CL",
    "CN",
    "CO",
    "CY",
    "CZ",
    "DE",
    "DK",
    "EE",
    "EG",
    "ES",
    "ET",
    "EU",
    "FI",
    "FR",
    "GB",
    "GH",
    "GR",
    "HK",
    "HR",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JP",
    "KE",
    "KR",
    "KW",
    "LK",
    "LT",
    "LU",
    "LV",
    "MA",
    "MU",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NG",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PE",
    "PH",
    "PK",
    "PL",
    "PT",
    "QA",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "TH",
    "TN",
    "TR",
    "TW",
    "TZ",
    "UA",
    "UG",
    "US",
    "VE",
    "VN",
    "ZA",
    "ZM",
    "ZW",
]

NEWS_CORP_ACTIVITIES: list[str] = [
    "credit_ratings",
    "dividends",
    "earnings",
    "earnings_calls",
    "esg",
    "insider_trading",
    "ipo",
    "management",
    "mergers_and_acquisitions",
    "ownership_changes",
    "recommendation",
    "share_buybacks",
    "strategy_business_products",
]

NEWS_ECONOMIC_CATEGORIES: list[str] = [
    "business",
    "consumer",
    "gdp",
    "government",
    "health",
    "housing",
    "labor",
    "money",
    "prices",
    "taxes",
    "trade",
]

NEWS_MARKETS: list[str] = [
    "bond",
    "corp_bond",
    "crypto",
    "economic",
    "etf",
    "forex",
    "futures",
    "index",
    "stock",
]

NEWS_SECTORS: list[str] = [
    "Commercial Services",
    "Communications",
    "Consumer Durables",
    "Consumer Non-Durables",
    "Consumer Services",
    "Distribution Services",
    "Electronic Technology",
    "Energy Minerals",
    "Finance",
    "Government",
    "Health Services",
    "Health Technology",
    "Industrial Services",
    "Miscellaneous",
    "Non-Energy Minerals",
    "Process Industries",
    "Producer Manufacturing",
    "Retail Trade",
    "Technology Services",
    "Transportation",
    "Utilities",
]

TIMEFRAMES: dict[str, str] = {
    "1m": "1",
    "5m": "5",
    "15m": "15",
    "30m": "30",
    "1h": "60",
    "2h": "120",
    "4h": "240",
    "1d": "1D",
    "1w": "1W",
    "1M": "1M",
}
